<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Estoqmov extends \Application\Entity\Estoqmov implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'codEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'dataEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'doctoEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'serieEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'quantEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'vlunitEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'vlcompraEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'tipoEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'obsEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'estoqueEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'ddelete', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'dupdate', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'dinsert', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'programa', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'estacao', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'usuario', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'custoEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'tipoMovimentoEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'vlmedioEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'codClien', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'codDoc', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'operacao', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'nota', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'codLoc', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'pedido', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'codProd'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'codEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'dataEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'doctoEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'serieEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'quantEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'vlunitEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'vlcompraEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'tipoEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'obsEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'estoqueEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'ddelete', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'dupdate', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'dinsert', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'programa', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'estacao', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'usuario', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'custoEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'tipoMovimentoEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'vlmedioEstmv', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'codClien', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'codDoc', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'operacao', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'nota', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'codLoc', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'pedido', '' . "\0" . 'Application\\Entity\\Estoqmov' . "\0" . 'codProd'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Estoqmov $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodEstmv()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCodEstmv();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodEstmv', []);

        return parent::getCodEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEstmv($dataEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEstmv', [$dataEstmv]);

        return parent::setDataEstmv($dataEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataEstmv', []);

        return parent::getDataEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoctoEstmv($doctoEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoctoEstmv', [$doctoEstmv]);

        return parent::setDoctoEstmv($doctoEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoctoEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoctoEstmv', []);

        return parent::getDoctoEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerieEstmv($serieEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerieEstmv', [$serieEstmv]);

        return parent::setSerieEstmv($serieEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerieEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerieEstmv', []);

        return parent::getSerieEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantEstmv($quantEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantEstmv', [$quantEstmv]);

        return parent::setQuantEstmv($quantEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantEstmv', []);

        return parent::getQuantEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlunitEstmv($vlunitEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlunitEstmv', [$vlunitEstmv]);

        return parent::setVlunitEstmv($vlunitEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlunitEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlunitEstmv', []);

        return parent::getVlunitEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlcompraEstmv($vlcompraEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlcompraEstmv', [$vlcompraEstmv]);

        return parent::setVlcompraEstmv($vlcompraEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlcompraEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlcompraEstmv', []);

        return parent::getVlcompraEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoEstmv($tipoEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoEstmv', [$tipoEstmv]);

        return parent::setTipoEstmv($tipoEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoEstmv', []);

        return parent::getTipoEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setObsEstmv($obsEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObsEstmv', [$obsEstmv]);

        return parent::setObsEstmv($obsEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getObsEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObsEstmv', []);

        return parent::getObsEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstoqueEstmv($estoqueEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstoqueEstmv', [$estoqueEstmv]);

        return parent::setEstoqueEstmv($estoqueEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstoqueEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstoqueEstmv', []);

        return parent::getEstoqueEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setDdelete($ddelete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDdelete', [$ddelete]);

        return parent::setDdelete($ddelete);
    }

    /**
     * {@inheritDoc}
     */
    public function getDdelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDdelete', []);

        return parent::getDdelete();
    }

    /**
     * {@inheritDoc}
     */
    public function setDupdate($dupdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDupdate', [$dupdate]);

        return parent::setDupdate($dupdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDupdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDupdate', []);

        return parent::getDupdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDinsert($dinsert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDinsert', [$dinsert]);

        return parent::setDinsert($dinsert);
    }

    /**
     * {@inheritDoc}
     */
    public function getDinsert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDinsert', []);

        return parent::getDinsert();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrograma($programa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrograma', [$programa]);

        return parent::setPrograma($programa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrograma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrograma', []);

        return parent::getPrograma();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstacao($estacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstacao', [$estacao]);

        return parent::setEstacao($estacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstacao', []);

        return parent::getEstacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustoEstmv($custoEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustoEstmv', [$custoEstmv]);

        return parent::setCustoEstmv($custoEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustoEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustoEstmv', []);

        return parent::getCustoEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoMovimentoEstmv($tipoMovimentoEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoMovimentoEstmv', [$tipoMovimentoEstmv]);

        return parent::setTipoMovimentoEstmv($tipoMovimentoEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoMovimentoEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoMovimentoEstmv', []);

        return parent::getTipoMovimentoEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlmedioEstmv($vlmedioEstmv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlmedioEstmv', [$vlmedioEstmv]);

        return parent::setVlmedioEstmv($vlmedioEstmv);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlmedioEstmv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlmedioEstmv', []);

        return parent::getVlmedioEstmv();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodClien(\Application\Entity\Cliente $codClien = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodClien', [$codClien]);

        return parent::setCodClien($codClien);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodClien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodClien', []);

        return parent::getCodClien();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodDoc(\Application\Entity\Docto $codDoc = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodDoc', [$codDoc]);

        return parent::setCodDoc($codDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodDoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodDoc', []);

        return parent::getCodDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperacao(\Application\Entity\Operacao $operacao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperacao', [$operacao]);

        return parent::setOperacao($operacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperacao', []);

        return parent::getOperacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setNota(\Application\Entity\Nota $nota = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNota', [$nota]);

        return parent::setNota($nota);
    }

    /**
     * {@inheritDoc}
     */
    public function getNota()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNota', []);

        return parent::getNota();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodLoc(\Application\Entity\Local $codLoc = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodLoc', [$codLoc]);

        return parent::setCodLoc($codLoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodLoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodLoc', []);

        return parent::getCodLoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setPedido(\Application\Entity\Pedido $pedido = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPedido', [$pedido]);

        return parent::setPedido($pedido);
    }

    /**
     * {@inheritDoc}
     */
    public function getPedido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPedido', []);

        return parent::getPedido();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodProd(\Application\Entity\Produto $codProd = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodProd', [$codProd]);

        return parent::setCodProd($codProd);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodProd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodProd', []);

        return parent::getCodProd();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function arrayToObject($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'arrayToObject', [$data]);

        return parent::arrayToObject($data);
    }

}
