<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Parctitulos extends \Application\Entity\Parctitulos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'codTit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'parcelaParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'valorParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vlpagoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vljurosParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vldescontoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vlcorrecaoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vlsaldoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vlcomissaoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vlchequeParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'venctoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'dtpagtoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'pagtoidParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'inpagtoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'statusParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'ddelete', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'dinsert', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'dupdate', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'usuario', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'programa', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'estacao', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'valorTabelaParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vldescontoComissaoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'motivo'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'codTit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'parcelaParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'valorParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vlpagoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vljurosParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vldescontoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vlcorrecaoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vlsaldoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vlcomissaoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vlchequeParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'venctoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'dtpagtoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'pagtoidParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'inpagtoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'statusParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'ddelete', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'dinsert', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'dupdate', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'usuario', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'programa', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'estacao', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'valorTabelaParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'vldescontoComissaoParctit', '' . "\0" . 'Application\\Entity\\Parctitulos' . "\0" . 'motivo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Parctitulos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodTit($codTit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodTit', [$codTit]);

        return parent::setCodTit($codTit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodTit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodTit', []);

        return parent::getCodTit();
    }

    /**
     * {@inheritDoc}
     */
    public function setParcelaParctit($parcelaParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParcelaParctit', [$parcelaParctit]);

        return parent::setParcelaParctit($parcelaParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getParcelaParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParcelaParctit', []);

        return parent::getParcelaParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorParctit($valorParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorParctit', [$valorParctit]);

        return parent::setValorParctit($valorParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorParctit', []);

        return parent::getValorParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlpagoParctit($vlpagoParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlpagoParctit', [$vlpagoParctit]);

        return parent::setVlpagoParctit($vlpagoParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlpagoParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlpagoParctit', []);

        return parent::getVlpagoParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setVljurosParctit($vljurosParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVljurosParctit', [$vljurosParctit]);

        return parent::setVljurosParctit($vljurosParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getVljurosParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVljurosParctit', []);

        return parent::getVljurosParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setVldescontoParctit($vldescontoParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVldescontoParctit', [$vldescontoParctit]);

        return parent::setVldescontoParctit($vldescontoParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getVldescontoParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVldescontoParctit', []);

        return parent::getVldescontoParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlcorrecaoParctit($vlcorrecaoParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlcorrecaoParctit', [$vlcorrecaoParctit]);

        return parent::setVlcorrecaoParctit($vlcorrecaoParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlcorrecaoParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlcorrecaoParctit', []);

        return parent::getVlcorrecaoParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlsaldoParctit($vlsaldoParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlsaldoParctit', [$vlsaldoParctit]);

        return parent::setVlsaldoParctit($vlsaldoParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlsaldoParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlsaldoParctit', []);

        return parent::getVlsaldoParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlcomissaoParctit($vlcomissaoParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlcomissaoParctit', [$vlcomissaoParctit]);

        return parent::setVlcomissaoParctit($vlcomissaoParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlcomissaoParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlcomissaoParctit', []);

        return parent::getVlcomissaoParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlchequeParctit($vlchequeParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlchequeParctit', [$vlchequeParctit]);

        return parent::setVlchequeParctit($vlchequeParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlchequeParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlchequeParctit', []);

        return parent::getVlchequeParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setVenctoParctit($venctoParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVenctoParctit', [$venctoParctit]);

        return parent::setVenctoParctit($venctoParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getVenctoParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVenctoParctit', []);

        return parent::getVenctoParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtpagtoParctit($dtpagtoParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtpagtoParctit', [$dtpagtoParctit]);

        return parent::setDtpagtoParctit($dtpagtoParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtpagtoParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtpagtoParctit', []);

        return parent::getDtpagtoParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagtoidParctit($pagtoidParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagtoidParctit', [$pagtoidParctit]);

        return parent::setPagtoidParctit($pagtoidParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagtoidParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagtoidParctit', []);

        return parent::getPagtoidParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setInpagtoParctit($inpagtoParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInpagtoParctit', [$inpagtoParctit]);

        return parent::setInpagtoParctit($inpagtoParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getInpagtoParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInpagtoParctit', []);

        return parent::getInpagtoParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusParctit($statusParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusParctit', [$statusParctit]);

        return parent::setStatusParctit($statusParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusParctit', []);

        return parent::getStatusParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDdelete($ddelete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDdelete', [$ddelete]);

        return parent::setDdelete($ddelete);
    }

    /**
     * {@inheritDoc}
     */
    public function getDdelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDdelete', []);

        return parent::getDdelete();
    }

    /**
     * {@inheritDoc}
     */
    public function setDinsert($dinsert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDinsert', [$dinsert]);

        return parent::setDinsert($dinsert);
    }

    /**
     * {@inheritDoc}
     */
    public function getDinsert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDinsert', []);

        return parent::getDinsert();
    }

    /**
     * {@inheritDoc}
     */
    public function setDupdate($dupdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDupdate', [$dupdate]);

        return parent::setDupdate($dupdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDupdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDupdate', []);

        return parent::getDupdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrograma($programa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrograma', [$programa]);

        return parent::setPrograma($programa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrograma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrograma', []);

        return parent::getPrograma();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstacao($estacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstacao', [$estacao]);

        return parent::setEstacao($estacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstacao', []);

        return parent::getEstacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorTabelaParctit($valorTabelaParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorTabelaParctit', [$valorTabelaParctit]);

        return parent::setValorTabelaParctit($valorTabelaParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorTabelaParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorTabelaParctit', []);

        return parent::getValorTabelaParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setVldescontoComissaoParctit($vldescontoComissaoParctit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVldescontoComissaoParctit', [$vldescontoComissaoParctit]);

        return parent::setVldescontoComissaoParctit($vldescontoComissaoParctit);
    }

    /**
     * {@inheritDoc}
     */
    public function getVldescontoComissaoParctit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVldescontoComissaoParctit', []);

        return parent::getVldescontoComissaoParctit();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotivo(\Application\Entity\MotivoNota $motivo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotivo', [$motivo]);

        return parent::setMotivo($motivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotivo', []);

        return parent::getMotivo();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function arrayToObject($data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'arrayToObject', [$data]);

        return parent::arrayToObject($data);
    }

}
