<?php

namespace Application\Entity;

/**
 * PedidoitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoitRepository extends \Doctrine\ORM\EntityRepository{
    
    public function listPorPedidoId(int $pedidoId){
        $qb = $this->createQueryBuilder('pit');
        return $qb->select('pit, pr, tp')->innerJoin('pit.codPed', 'p')
                ->innerJoin('pit.codProd', 'pr')->innerJoin('pr.tipoProduto', 'tp')->where('(p.codPed = :pedidoId)')
                ->setParameter('pedidoId', $pedidoId)->getQuery()->getResult();    
    }
    
    /**
     * Pesquisa Itens do Pedido por id do Pedido
     * @param string $idPedido
     * @return array
     */
    public function findByPedidoId(string $idPedido){
        $qb = $this->createQueryBuilder('i');
        return $qb->select('i')->innerJoin('i.codPed', 'p')->where('i.codPed = :codPed')
                ->setParameter('codPed', $idPedido)->getQuery()->getResult();
    }
    
    public function updateTecnicoCascade(int $pedidoId, int $tecnicoId){
        $qb = $this->createQueryBuilder('pit');
        $q = $qb->update()
            ->set('pit.codVend', ':tecnicoId')
            ->where('pit.codPed = :pedidoId')
            ->setParameter('tecnicoId', $tecnicoId)->setParameter('pedidoId', $pedidoId)
            ->getQuery();
        return $q->execute();
    }    
}
