<div id="dialog-warning" title="<?php echo $this->translate('Atenção')?>" style="display:none">
    <div class="alert alert-warning" role="alert"><p ><span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span></p></div>
</div>
<div id="dialog-info" title="<?php echo $this->translate('Informação')?>" style="display:none">
    <div class="alert alert-info" role="alert"><p ><span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span></p></div>
</div>

<div id="dialog-error" title="<?php echo $this->translate('Erro')?>" style="display:none">
    <div class="alert alert-error" role="alert"><p ><span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span></p></div>
</div>
<div id="dialog-success" title="<?php echo $this->translate('Sucesso')?>" style="display:none">
    <div class="alert alert-success" role="alert"><p ><span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span></p></div>
</div>
<div id="dialog-loading" title="<?php echo $this->translate('Loading')?>" style="display:none">
    <div class="alert alert-warning" role="alert"><p ><span class="ui-icon ui-icon-circle-check" style="float:left; margin:0 7px 50px 0;"></span></p></div>
    <div id="loading"><img src="/img/giphy2.gif" /></div>    
</div>