<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <?= $this->headTitle('Sistema Onix ')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>
        <?= $this->headMeta()
            ->appendName('description', 'Sistema Onix - Software de Gestão')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>
        <?= $this->headMeta()
            ->appendName('empresa', 'Sistema Onix')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>
        <?= $this->headMeta()
            ->appendName('author', 'Sistema Onix - Developement')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'href' => $this->basePath() . 'imgSite/icons/favicon.png'])
            ->prependStylesheet($this->basePath('css/bootstrap.css'))
            ->prependStylesheet($this->basePath('css/custom.css'))
            ->prependStylesheet($this->basePath('css/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/animate.min.css'))
                
        ?>
        <!--Your custom colour override-->
        <link href="#" id="colour-scheme" rel="stylesheet">

        <!-- Le fav and touch icons - @todo: fill with your icons or remove -->
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="imgSite/icons/114x114.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="imgSite/icons/72x72.png">
        <link rel="apple-touch-icon-precomposed" href="imgSite/icons/default.png">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300|Rambla|Calligraffitti' rel='stylesheet' type='text/css'>
        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('jsSite/html5.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ?>
    </head>
<body class="login">
    <div>
        <a class="hiddenanchor" id="signup"></a>
        <a class="hiddenanchor" id="signin"></a>

        <div class="login_wrapper">
            <?php echo $this->content; ?>
        </div>
    </div>
</body>
</html>
