<!-- Services -->
<div class="block features">
  <h2 class="title-divider"><span>Nossos <span class="de-em">Produtos</span></span> <small>Abaixo alguns de nossos produtos.</small></h2>
  <ul class="thumbnails">
    <li class="span3"> <a href="features.htm"><img src="imgSite/features/feature-1.png" alt="Produto 1" /></a>
      <h3 class="title"><a href="features.htm">Dispositivos <span class="de-em">Móveis</span></a></h3>
      <p>Desenvolvimento de Sistemas para dispositivos móveis android. Desenvolvemos qualquer aplicativo para dispositivos com o sistema operacional ANDROID (Tablets, Celulares).</p>
    </li>
    <li class="span3"> <a href="features.htm"><img src="imgSite/features/feature-2.png" alt="Produto 2" /></a>
      <h3 class="title"><a href="features.htm">WEB <span class="de-em">2.0</span></a></h3>
      <p>Desenvolvimento de Sistemas para WEB 2.0, Sites Institucionais, Desenvolvimento de WebServices, entre outros. Desenvolvimento WEB 2.0 para qualquer necessidade de sua empresa.</p>
    </li>
    <li class="span3"> <a href="features.htm"><img src="imgSite/features/feature-3.png" alt="Produto 3" /></a>
      <h3 class="title"><a href="features.htm">Suporte <span class="de-em">Técnico</span></a></h3>
      <p>Planos para suporte técnico dos produtos adquiridos. Todos os produtos adquiridos terão um suporte técnico para implantação, podendo ser extendido.</p>
    </li>
    <li class="span3"> <a href="/index.php?page=sistemaOnix&slider=1"><img src="imgSite/features/feature-4.png" alt="Produto 4" /></a>
      <h3 class="title"><a href="/index.php?page=sistemaOnix&slider=1">Automatização <span class="de-em">Comercial</span></a></h3>
      <p>Sistema Onix. Produto destinado as empresas que possuem a necessidade de automatização do negócio. NF-e, NFS-e, ECF, Emissão de Boletos, Controle de Estoque, Controle Financeiro.</p>
    </li>
  </ul>
</div>

<div class="post">
    <h1 class="title">Sistema Onix de Automação Comercial</h1>
    <div class="entry">
        <p><img alt="Estrutura" src="/imgSite/estrutura330_142.png" style="border: 0; width:300px;height:140px;"/>
        <br/>	
        Sistema Onix é um sistema leve e robusto, feito com as melhores e mais avançadas técnicas de desenvolvimento.
        Tem como base tecnologia SQL, Cliente-servidor em camadas. 
        Faz uso de software livre, dando ao cliente a garantia de uso de um software original sem custo com licensa.
        Sistema modular, trabalha com o conceito de departamentalização, disponibilizando a sua empresa 
        conceito de controle com base teorias administrativas e fiscais. Sistema lhe garante total controle com
        segurança dos processos e permite o retorno de informações para os diversos níveis: operacional, gerencial e
        apoio a decisões.
        O sistema atende pequenas e médias empresas do ramo de autopeças e serviços.
        Sistema Onix possui integração transparente entre os módulos como: estoque, financeiro, fiscal, vendas e outros.
        Sistema Onix possui o módulo de interação também com NF-e, NFS-e, CTé, NFC-e, ECF, SPED, Sintegra. Podendo ainda exportar fazer integração com outros sistemas, exportação
        de informações transparente.
        Venha conhecer Sistema Onix e faça a sua escolha segura e conciente. <br/>
        Veja <a href="./index.php?page=fluxograma&slider=1"><b>fluxograma</b></a> do sistema Sistema Onix.
        <br/>			
        Equipe Sistema Onix...
        </p>
        <ul class="inline links">
            <li><a href="/index.php?page=sistemaOnix&slider=1" class="btn btn-mini"><i class="icon-circle-arrow-right"></i> Saiba Mais</a></li>
        </ul>
    </div>
</div>    
